/**
 * The ambient backdrop: deep space, a star field, one drifting aurora and a
 * film of noise.
 *
 * Every layer is CSS. No canvas, no requestAnimationFrame, no library, no
 * image — which means it costs nothing on the main thread, cannot fail to
 * load, and keeps animating while React is busy streaming a reply. The star
 * field is the only part generated in JS, and only once: positions are fixed
 * at module load so the layout never reflows and a re-render never reshuffles
 * the sky.
 *
 * It sits at the root behind everything, `fixed` and `pointer-events-none`, so
 * no component has to know it exists.
 */

/** Enough to read as a field without becoming a texture. */
const STAR_COUNT = 150;

/**
 * Deterministic pseudo-random, seeded per index.
 *
 * `Math.random()` would give a different sky on every reload, and — worse —
 * a different one per hot reload during development, which makes visual
 * regressions impossible to spot. The exact constants do not matter, only
 * that the sequence is stable and well spread.
 */
function noise(seed: number): number {
  const x = Math.sin(seed * 127.1 + 311.7) * 43758.5453;
  return x - Math.floor(x);
}

interface Star {
  left: string;
  top: string;
  size: string;
  /** 4-10s, so neighbouring stars visibly drift out of step. */
  duration: string;
  /** Staggered start, so they do not all pulse together on first paint. */
  delay: string;
  peak: number;
}

const STARS: Star[] = Array.from({ length: STAR_COUNT }, (_, i) => {
  const bright = noise(i * 3 + 2);
  return {
    left: `${noise(i * 3) * 100}%`,
    top: `${noise(i * 3 + 1) * 100}%`,
    // A few larger ones give the field depth; most stay sub-pixel-ish.
    size: `${bright > 0.93 ? 2 : 1}px`,
    duration: `${4 + noise(i * 3 + 4) * 6}s`,
    delay: `${noise(i * 3 + 5) * 8}s`,
    peak: 0.2 + bright * 0.4,
  };
});

export function SpaceBackground() {
  return (
    <div aria-hidden className="nova-space">
      {/* Radial gradient from the void centre out to black. */}
      <div className="nova-space-void" />

      {/* One slow aurora. Barely visible by design: it exists to keep the
          background from reading as flat black, not to be looked at. */}
      <div className="nova-space-aurora" />

      <div className="nova-space-stars">
        {STARS.map((star, i) => (
          <span
            key={i}
            className="nova-star"
            style={{
              left: star.left,
              top: star.top,
              width: star.size,
              height: star.size,
              animationDuration: star.duration,
              animationDelay: star.delay,
              // Read by the keyframes, so each star peaks at its own
              // brightness rather than every star hitting the same value.
              ['--star-peak' as string]: star.peak,
            }}
          />
        ))}
      </div>

      {/* A film of grain over everything. Pure black gradients band visibly on
          an OLED panel; 2% noise is below the threshold of notice and breaks
          the banding up. Generated by an SVG filter, so there is no image to
          fetch and it stays sharp at any density. */}
      <div className="nova-space-noise" />
    </div>
  );
}
